### ISSUE TITLE
Unable to build mazelib as dependency for python versions > 3.10

### ISSUE THREAD

**Issue by smorad** [john-science/mazelib#140]
```
conda create -n popgym python=3.11
git clone https://github.com/proroklab/popgym
cd popgym
pip install -e .
```
```
...
            clang: numpy/core/src/multiarray/scalarapi.c
            clang: numpy/core/src/multiarray/temp_elide.c
            clang: numpy/core/src/multiarray/vdot.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-11.0-arm64-3.1/numpy/core/src/umath/loops.c
            clang: numpy/core/src/umath/extobj.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/umath/ufunc_type_resolution.c
            clang: build/src.macosx-11.0-arm64-3.1/numpy/core/src/npymath/ieee754.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/array_assign.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/ucsnarrow.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/cblasfuncs.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            error: Command "clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/smorad/miniforge3/envs/popgym-gymnasium2/include -arch arm64 -fPIC -O2 -isystem /Users/smorad/miniforge3/envs/popgym-gymnasium2/include -arch arm64 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/umath -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/smorad/miniforge3/envs/popgym-gymnasium2/include/python3.11 -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/common -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/common -Ibuild/src.macosx-11.0-arm64-3.1/numpy/core/src/npymath -c numpy/core/src/multiarray/buffer.c -o build/temp.macosx-11.0-arm64-cpython-311/numpy/core/src/multiarray/buffer.o -MMD -MF build/temp.macosx-11.0-arm64-cpython-311/numpy/core/src/multiarray/buffer.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        error: subprocess-exited-with-error

        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.

            `setup.py clean` is not supported, use one of the following instead:

              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)

            Add `--force` to your command to use it anyway if you must (unsupported).

            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/installer.py", line 97, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/smorad/miniforge3/envs/popgym-gymnasium2/bin/python3.11', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/tmpn05ozhry', '--quiet', 'numpy<=1.16.4,>=1.13.1']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-install-erua8kqp/mazelib_3868e05c0c2d463da443765730dbb63f/setup.py", line 60, in <module>
          setup(
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/popgym-gymnasium2/lib/python3.11/site-packages/setuptools/installer.py", line 99, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/smorad/miniforge3/envs/popgym-gymnasium2/bin/python3.11', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/tmpn05ozhry', '--quiet', 'numpy<=1.16.4,>=1.13.1']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Where as python version 3.10 succeeds:
```
conda create -n popgym python=3.11
git clone https://github.com/proroklab/popgym
cd popgym
pip install -e .
```

This error occurs when `setup.cfg` lists `mazelib` as a dependency:
```
[metadata]
name = popgym
description = A collection of partially-observable procedural gym environments
author = Steven Morad
version = 0.0.2
license = MIT
readme = README.md
# Remove 3.10 limit when mazelib fixes its build process
# to work with 3.11
requires-python = >=3.7 <=3.10
keywords = gym, pomdp, partially observable, reinforcement learning, rl

[options]
packages = find:
install_requires = 
    numpy
    gym==0.24.0
    mazelib

[options.extras_require]
baselines = 
    torch
    opt_einsum
    wandb
    dnc
    einops
    ray[rllib]==2.0.0
```

**Comment by geneshki** [comment]
Not sure if possible, but if your module - popgym - uses [mazelib-alt](https://pypi.org/project/mazelib-alt/) instead, it might build. It is listed in Pypi as 

> Modified to have less strict dependency versions.

**Comment by john-science** [comment]
> Not sure if possible, but if your module - popgym - uses [mazelib-alt](https://pypi.org/project/mazelib-alt/) instead, it might build. It is listed in Pypi as
> 
> > Modified to have less strict dependency versions.

OMG.  `mazelib-alt` exists.

Okay, is that repo on github?  I can look at what they changed.

**Comment by noah-hein** [comment]
I've got the same issue, I can't install for 3.11. I forked some of this repo to cut out some of the dependencies for 3.11. I have no idea how licensing works (stressing out about it a little), but an update to 3.11 would solve a lot of problems and allow me to not worry about properly accrediting this repo.

Or a change to an MIT license would work too.

**Comment by john-science** [comment]
https://pypi.org/project/mazelib/0.9.14/#files
